language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: NDUsKSQ8LXyvISS1nM56Sl3yzV/dJONwILDgniqmM84Bwt0LhEijU41fWps9cABSa4aUwXSyQ6SvaxuofuNIXTmNDmbrIv7Xh/WUk7afZ6QZ04GuBQro8CFb3BL76Kqbpb0c/Y3ndtprUWPIAzhbru3SrVdlFh97W3Ds6YswUZTRotnfnnB0iTcHua7pmNpOmxiMH4/xzq//unyGN5ggd+Z/nvrUFLUu/+u2CmndaIDaua+IFiOMw1g38Ayu6Ghj8aWC2AIqchHAMacW8MhK7SPJKQ3rEZNYeV0TGpR2aYPPqbYh477Ha4nZe2k8d9tJSBFDNswtDVxwej6g00rP++ElDmuNvuDxvCuvITKJtrVI2m64dX222eRk7w0mc1lN8z3ZoE9B5yp1SSWuSYaYO7+lkv/oDaeWOl6zdaupR0vAQYoP8tbk7CYI3U1NdE5ZdjplRznpnzDFsCXR4cwq+m5hoAtqTqMwZiSHD0U/shOaT06zJfPvXHSpgNXX4/1NWDOLOVTVNjL5IsayJLer5fNvM/W4ZaXF6yzRGDNefsyxYNVsC++r05hCZZT7ai6nD0sNhMfRJ53rzOVSSPzCCLSRaTw/6tngieaoyrQWIcYzbXrT9AEmlmNxSxIKuu2mkDpegMQlLwgFUgiw/DR3fs+us2ehOTw9tkpAZfPU9Xw=
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    rooms:
      secure: QD46Qnyjx73ztkGCjx+jMnQWlx5II6rBSv/gf/o2pRJEJUuz9vYQn2rdjtzHukn3p2GIOBUKKrx/Jl7zphcYvtEO7yAvVDUqUhnffgPH42C8C4hVI9R3PAriFMxffuJm3kfnZvOHF3KFro8sK6XoorlaiZ14noPVWtNFj14cajOGs7fak4f9fzi/mi4CP+VvE1DP9lpU2e74SHKNk58OqxfTyz9qHo9N87JTJuVDs3T1btb7jUviB31EjtPnUTfd+J6aoEfun+J+LIKi+VxSBAjJPtOtRWo6ztPt8PMErAK60fgVo42KtP1CiTnwfmBu+035hiKXNNt8x1BgfFavfIUnhU2G8V5n9y+L+11qMzzAdIL8YBtHN/r/cA44INtnBhAUjRihUTC9ahlQ1Q3PmAvU5wNOVN9cPRFJ5HemoGPRb3SPRE2R7IlRNucXCkBOJH1u9o5IH04CKfuWWEfWtJnFizPxu9VoY5cZV2unW5ya1SjK3lq36wzcGdMh9pELITRLg2jskhdAvJAdmIvGaJZHJXQP7CVOkaLbAhezJ6x32uavRNKHqB27mqOfkFD6e6G95uMPWZtyr+joJDrx1gmofDpraky8s8162PCTsijPTFlibrgfEIV/ei48jpwOEUX0GFEvanxiPQoB2wm8mSnolHsC538xVux9tkCsEQg=
    on_success: always
    on_failure: always
    on_error: always
    template:
      - 'Build %{result}: %{repository_slug}'
      - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) on %{branch} by %{author} %{result} in %{duration}'
